# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/user/Desktop/OCD/OCD.cache/wt [current_project]
set_property parent.project_path C:/Users/user/Desktop/OCD/OCD.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/user/Desktop/OCD/OCD.srcs/ip [current_project]
set_property ip_output_repo c:/Users/user/Desktop/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet C:/Users/user/Desktop/OCD/OCD.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/user/Desktop/OCD/OCD.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/user/Desktop/project_2/project_2.srcs/sources_1/new/transmit_debouncing.v
  C:/Users/user/Desktop/project_2/project_2.srcs/sources_1/new/transmitter.v
  C:/Users/user/Desktop/project_2/project_2.srcs/sources_1/new/UART_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/user/Desktop/OCD/OCD.srcs/constrs_1/imports/UART serial communication/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/user/Desktop/OCD/OCD.srcs/constrs_1/imports/UART serial communication/Basys3_Master.xdc}}]


synth_design -top UART_top -part xc7a35tcpg236-3


write_checkpoint -force -noxdef UART_top.dcp

catch { report_utilization -file UART_top_utilization_synth.rpt -pb UART_top_utilization_synth.pb }
